<?php

namespace Tests;

use App\LRUCache;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

class LRUCacheTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    #[Test]
    public function itShouldCorrectlyRemoveFirstAfterPuttingThirdElement():void
    {
        $solution = new LRUCache(2);
        $solution->put(1, 1);
        $solution->put(2, 2);
        self::assertSame(
            1,
            $solution->get(1),
        );
        $solution->put(3, 3);
        $solution->get(2);
        $solution->put(4, 4);
        $solution->get(1);
        $solution->get(3);
        $solution->get(4);
    }

    #[Test]
    public function putGetPutGetGet():void
    {
        $solution = new LRUCache(1);
        $solution->put(2, 1);
        self::assertSame(
            1,
            $solution->get(2),
        );
        $solution->put(3, 2);
        $solution->get(2);
        $solution->get(3);
    }


}
